language: node_js
node_js:
  - 8.6.0
install:
  - npm install
  - npm run build
script:
  - npm run lint
  - npm run test:unit
deploy:
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: T6xjxLuRTajsgqhEJUXrXUx4tEVdQM2f7EdnBjOLSH4UHRc0AXTPWOz4Q9cAnVvhwUiBy39xs39Vt3X4KBqGrqkL0iRb/F+PPi0ReIotK2VftlgSaXD+IlgeGYmQEMy6WpaDmkgz8yPzJ7ohq7uvUmyG1rbtvyWsk1BfusKaX8YYrLlEldvd2u0LveRo6CJpwI5e9xdFPOhRzMHsExJpDdPBr1v6/AOrrKyoZTJCLuRayXP9nQg1q1cQsH2tf+5Ivfeh9vWXvSjh8pSLQYZM8/f5t3G+nvhCBpkqpiNr7WJl+M7n4X5G2ROa79r5qaywAQVRx2YTxFiR5vzFmrFtVJrGSI362pkDkP7eok699xNECDAUciXj7Cn+eG+ZzDvZi41sx6poc4dPtTu5B2y6P1eQ57ndIwfU2uWBPdLz5lkeaT1/fw8jOLaNycHTO0VESI4RoXg/57zxhoye+hUA/upDJa5zyXLM/+2LDhxxGeyKbBaBLIWH5G3jzOqg/x1W2YR+/mzsno4FH51a5zwsanWn2E+QXskS8ey/gJqVFA3c6GhRlaQlJeQBGyXq74G0nKyIQlejdKijP9TujqPZfYkZ2TGYcwDYH8pyFMAhBwQSWyUhe1RIv86XAi8BbIjy14az9BVHC2uggmKOSiAzwQ/KWs6HwhwoTFjgXxsB2Nk=

    app:
      master: yasli-deploy